#!/bin/sh
# Container entrypoint — generates /srv/runtime-config.js from ARGUSLOG_WEB_* env vars
# before exec-ing Caddy. The web bundle reads window.__ARGUSLOG_CONFIG__ at startup, so
# changing a Keycloak URL or API base just means setting the env var and restarting the
# container — no rebuild needed.
#
# Empty values are written as empty strings; the JS-side env.ts treats those as "unset"
# and falls back to VITE_* build-time defaults (useful for dev / staging-on-default
# arguslog.org URLs without setting every var explicitly).
#
# Why a single .js file instead of /config.json fetched by the SPA: fetching would
# block the first render on a round-trip; a script tag in index.html lets the bundle
# read its config synchronously at parse time.

set -eu

# Escape backslashes and double-quotes for safe embedding inside JS string literals.
esc() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

cat > /srv/runtime-config.js <<EOF
// Generated by runtime-config.sh at container startup. Do NOT hand-edit — restart
// the container after changing ARGUSLOG_WEB_* env vars.
window.__ARGUSLOG_CONFIG__ = {
  apiBaseUrl: "$(esc "${ARGUSLOG_WEB_API_BASE_URL:-}")",
  ingestBaseUrl: "$(esc "${ARGUSLOG_WEB_INGEST_BASE_URL:-}")",
  keycloakUrl: "$(esc "${ARGUSLOG_WEB_KEYCLOAK_URL:-}")",
  keycloakRealm: "$(esc "${ARGUSLOG_WEB_KEYCLOAK_REALM:-}")",
  keycloakClientId: "$(esc "${ARGUSLOG_WEB_KEYCLOAK_CLIENT_ID:-}")",
  dogfoodDsn: "$(esc "${ARGUSLOG_WEB_DOGFOOD_DSN:-}")",
  release: "$(esc "${ARGUSLOG_WEB_RELEASE:-}")"
};
EOF

exec caddy "$@"
