version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      mantine:
        patterns: ['@mantine/*']
      tanstack:
        patterns: ['@tanstack/*']
      types:
        patterns: ['@types/*']

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      spring:
        patterns:
          - 'org.springframework*'
          - 'org.springframework.boot:*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
